# Generated by Django 4.2.2 on 2024-12-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Номер дома"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "dealer_type",
                    models.CharField(
                        choices=[
                            ("FACTORY", "Завод"),
                            ("RETAIL", "Розничная сеть"),
                            ("INDIVIDUAL", "Индивидуальный предприниматель"),
                        ],
                        verbose_name="Тип звена торговой сети",
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Уровень иерархии в торговой сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дилер",
                "verbose_name_plural": "Дилеры",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "product_release_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
