# Generated by Django 4.2.2 on 2024-12-02 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("electronics_retail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь владелец",
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь владелец",
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="products",
            field=models.ManyToManyField(
                to="electronics_retail.products", verbose_name="Продукты"
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="shipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="electronics_retail.dealer",
                verbose_name="Поставщик",
            ),
        ),
    ]
